import { Injectable, NotFoundException } from '@nestjs/common';
import { InjectRepository } from '@nestjs/typeorm';
import PDFDocument from 'pdfkit';
import { Repository } from 'typeorm';
import { Booking } from '../../../database/entities/booking.entity';
import { TollCharge } from '../../../database/entities/toll-charge.entity';

@Injectable()
export class UserInvoiceService {
  constructor(
    @InjectRepository(Booking)
    private readonly bookingRepo: Repository<Booking>,
    @InjectRepository(TollCharge)
    private readonly tollRepo: Repository<TollCharge>,
  ) {}

  async buildPdfBuffer(bookingId: string, userId: string): Promise<Buffer> {
    const booking = await this.bookingRepo.findOne({
      where: { id: bookingId, user_id: userId },
      relations: {
        ambulance_type: true,
        ride_details: true,
        payments: true,
        driver_assignments: { driver: true },
      },
    });
    if (!booking) {
      throw new NotFoundException('Booking not found');
    }

    const tolls = await this.tollRepo.find({ where: { booking_id: bookingId } });
    const tollTotal = tolls.reduce(
      (s, t) => s + Number(t.amount ?? 0),
      0,
    );

    const assignment = (booking.driver_assignments ?? [])
      .filter((a) => a.is_current && a.accepted_at)
      .sort(
        (a, b) => b.assigned_at.getTime() - a.assigned_at.getTime(),
      )[0];

    const pay =
      (booking.payments ?? []).find((p) => p.status === 'success') ??
      (booking.payments ?? [])[0];

    const fare =
      booking.final_fare != null
        ? Number(booking.final_fare)
        : booking.estimated_fare != null
          ? Number(booking.estimated_fare)
          : 0;

    return new Promise((resolve, reject) => {
      const doc = new PDFDocument({ margin: 50 });
      const chunks: Buffer[] = [];
      doc.on('data', (c: Buffer) => chunks.push(c));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      doc.fontSize(18).text('One Click Ambulance — Invoice', {
        align: 'center',
      });
      doc.moveDown();
      doc.fontSize(10).fillColor('#444');
      doc.text(`Booking ID: ${booking.id}`);
      doc.text(`Date: ${booking.created_at.toISOString()}`);
      doc.text(`Status: ${booking.status}`);
      doc.moveDown();
      doc.text(
        `Ambulance type: ${booking.ambulance_type?.name ?? '—'}`,
      );
      if (assignment?.driver) {
        doc.text(`Driver: ${assignment.driver.name}`);
      }
      doc.moveDown();
      doc.text('Route');
      doc.text(`Pickup: ${booking.pickup_address ?? '—'}`);
      doc.text(`Drop: ${booking.drop_address ?? '—'}`);
      doc.moveDown();

      if (booking.ride_details) {
        doc.text('Trip');
        doc.text(
          `Distance (km): ${booking.ride_details.total_distance_km != null ? Number(booking.ride_details.total_distance_km) : '—'}`,
        );
        doc.text(
          `Duration (min): ${booking.ride_details.total_duration_min ?? '—'}`,
        );
        if (booking.ride_details.trip_started_at) {
          doc.text(`Started: ${booking.ride_details.trip_started_at}`);
        }
        if (booking.ride_details.trip_completed_at) {
          doc.text(`Completed: ${booking.ride_details.trip_completed_at}`);
        }
        doc.moveDown();
      }

      doc.text('Fare breakdown');
      doc.text(`Base fare (incl. estimate): ₹${fare.toFixed(2)}`);
      if (tolls.length > 0) {
        tolls.forEach((t) => {
          doc.text(
            `Toll — ${t.description ?? 'line'}: ₹${Number(t.amount).toFixed(2)}`,
          );
        });
        doc.text(`Tolls subtotal: ₹${tollTotal.toFixed(2)}`);
      }
      doc.moveDown();
      doc.fontSize(12).fillColor('#000');
      doc.text(`Total due / charged: ₹${(fare + tollTotal).toFixed(2)}`, {
        underline: true,
      });
      doc.moveDown();
      doc.fontSize(10).fillColor('#444');
      if (pay) {
        doc.text(`Payment status: ${pay.status}`);
        doc.text(`Method: ${pay.payment_method}`);
        if (pay.razorpay_payment_id) {
          doc.text(`Razorpay payment id: ${pay.razorpay_payment_id}`);
        }
      } else {
        doc.text('Payment: not recorded');
      }

      doc.moveDown(2);
      doc.fontSize(8).fillColor('#888').text('Generated by One Click Ambulance.', {
        align: 'center',
      });

      doc.end();
    });
  }
}
